-- MySQL Script generated by MySQL Workbench
-- Sun May  3 22:22:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SysAdminDemo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SysAdminDemo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SysAdminDemo` DEFAULT CHARACTER SET utf8 ;
USE `SysAdminDemo` ;

-- -----------------------------------------------------
-- Table `SysAdminDemo`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SysAdminDemo`.`Student` ;

CREATE TABLE IF NOT EXISTS `SysAdminDemo`.`Student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `EnrollmentDate` DATETIME NOT NULL,
  `cpr` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idtable1_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SysAdminDemo`.`Courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SysAdminDemo`.`Courses` ;

CREATE TABLE IF NOT EXISTS `SysAdminDemo`.`Courses` (
  `idCourses` INT NOT NULL AUTO_INCREMENT,
  `courseName` VARCHAR(45) NOT NULL,
  `ETCS` INT NOT NULL,
  `Description` VARCHAR(255) NOT NULL,
  `startDate` DATE NOT NULL,
  PRIMARY KEY (`idCourses`),
  UNIQUE INDEX `idCourses_UNIQUE` (`idCourses` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
